// <auto-generated />
using MBApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace MBApplication.Migrations
{
    [DbContext(typeof(MBAppContext))]
    [Migration("20180102224514_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("MBApplication.Data.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("FamilyName");

                    b.Property<string>("House");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<int>("Zip");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("MBApplication.Data.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<int?>("FamilyId");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("LastName");

                    b.Property<string>("MaritalStatus");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Telephone");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MBApplication.Data.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<int?>("MemberId");

                    b.Property<string>("MembershipBy");

                    b.Property<int?>("PremiseId");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.HasIndex("PremiseId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("MBApplication.Data.Premise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<string>("House");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("Telephone");

                    b.Property<string>("Type");

                    b.Property<string>("Website");

                    b.Property<int>("Zip");

                    b.HasKey("Id");

                    b.ToTable("Premises");
                });

            modelBuilder.Entity("MBApplication.Data.Member", b =>
                {
                    b.HasOne("MBApplication.Data.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId");
                });

            modelBuilder.Entity("MBApplication.Data.Membership", b =>
                {
                    b.HasOne("MBApplication.Data.Member", "Member")
                        .WithOne("Membership")
                        .HasForeignKey("MBApplication.Data.Membership", "MemberId");

                    b.HasOne("MBApplication.Data.Premise", "Premise")
                        .WithMany("Membership")
                        .HasForeignKey("PremiseId");
                });
#pragma warning restore 612, 618
        }
    }
}
